[theme]

# Primary accent for interactive elements
primaryColor = '#8D77E3'

# Background color for the main content area
backgroundColor = '#262139'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#B9CAF1'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"